import type { Metadata } from "next";
import "./globals.css";
import { AppProviders } from "@/components/providers/app-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="lg:max-w-screen-lg mx-auto">
        <AppProviders children={children} />
      </body>
    </html>
  );
}
